name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.2.1
      with:
        major_pattern: "Major:"
        minor_pattern: "Feature:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: semantic_version
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker Image
      env:
        VERSION: ${{steps.semantic_version.outputs.version}}
      run: |
        docker build -t smartiumtech/docker-graphql:$VERSION .
        docker build -t smartiumtech/docker-graphql:latest .
    - name: Push Docker Image
      env:
        VERSION: ${{steps.semantic_version.outputs.version}}
      run: |
        docker push smartiumtech/docker-graphql:$VERSION
        docker push smartiumtech/docker-graphql:latest
